//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace docbox.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DX_LOGGEREntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DX_LOGGEREntities object using the connection string found in the 'DX_LOGGEREntities' section of the application configuration file.
        /// </summary>
        public DX_LOGGEREntities() : base("name=DX_LOGGEREntities", "DX_LOGGEREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DX_LOGGEREntities object.
        /// </summary>
        public DX_LOGGEREntities(string connectionString) : base(connectionString, "DX_LOGGEREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DX_LOGGEREntities object.
        /// </summary>
        public DX_LOGGEREntities(EntityConnection connection) : base(connection, "DX_LOGGEREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<adminlog> adminlogs
        {
            get
            {
                if ((_adminlogs == null))
                {
                    _adminlogs = base.CreateObjectSet<adminlog>("adminlogs");
                }
                return _adminlogs;
            }
        }
        private ObjectSet<adminlog> _adminlogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<exceptionlog> exceptionlogs
        {
            get
            {
                if ((_exceptionlogs == null))
                {
                    _exceptionlogs = base.CreateObjectSet<exceptionlog>("exceptionlogs");
                }
                return _exceptionlogs;
            }
        }
        private ObjectSet<exceptionlog> _exceptionlogs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the adminlogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToadminlogs(adminlog adminlog)
        {
            base.AddObject("adminlogs", adminlog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the exceptionlogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToexceptionlogs(exceptionlog exceptionlog)
        {
            base.AddObject("exceptionlogs", exceptionlog);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DX_LOGGERModel", Name="adminlog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class adminlog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new adminlog object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static adminlog Createadminlog(global::System.Int64 id)
        {
            adminlog adminlog = new adminlog();
            adminlog.id = id;
            return adminlog;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> datetime
        {
            get
            {
                return _datetime;
            }
            set
            {
                OndatetimeChanging(value);
                ReportPropertyChanging("datetime");
                _datetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datetime");
                OndatetimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _datetime;
        partial void OndatetimeChanging(Nullable<global::System.DateTime> value);
        partial void OndatetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String docboxthread
        {
            get
            {
                return _docboxthread;
            }
            set
            {
                OndocboxthreadChanging(value);
                ReportPropertyChanging("docboxthread");
                _docboxthread = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("docboxthread");
                OndocboxthreadChanged();
            }
        }
        private global::System.String _docboxthread;
        partial void OndocboxthreadChanging(global::System.String value);
        partial void OndocboxthreadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String loglevel
        {
            get
            {
                return _loglevel;
            }
            set
            {
                OnloglevelChanging(value);
                ReportPropertyChanging("loglevel");
                _loglevel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("loglevel");
                OnloglevelChanged();
            }
        }
        private global::System.String _loglevel;
        partial void OnloglevelChanging(global::System.String value);
        partial void OnloglevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String logger
        {
            get
            {
                return _logger;
            }
            set
            {
                OnloggerChanging(value);
                ReportPropertyChanging("logger");
                _logger = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("logger");
                OnloggerChanged();
            }
        }
        private global::System.String _logger;
        partial void OnloggerChanging(global::System.String value);
        partial void OnloggerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String logmessage
        {
            get
            {
                return _logmessage;
            }
            set
            {
                OnlogmessageChanging(value);
                ReportPropertyChanging("logmessage");
                _logmessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("logmessage");
                OnlogmessageChanged();
            }
        }
        private global::System.String _logmessage;
        partial void OnlogmessageChanging(global::System.String value);
        partial void OnlogmessageChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DX_LOGGERModel", Name="exceptionlog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class exceptionlog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new exceptionlog object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static exceptionlog Createexceptionlog(global::System.Int64 id)
        {
            exceptionlog exceptionlog = new exceptionlog();
            exceptionlog.id = id;
            return exceptionlog;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private Nullable<global::System.DateTime> _date;
        partial void OndateChanging(Nullable<global::System.DateTime> value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String thread
        {
            get
            {
                return _thread;
            }
            set
            {
                OnthreadChanging(value);
                ReportPropertyChanging("thread");
                _thread = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("thread");
                OnthreadChanged();
            }
        }
        private global::System.String _thread;
        partial void OnthreadChanging(global::System.String value);
        partial void OnthreadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String loglevel
        {
            get
            {
                return _loglevel;
            }
            set
            {
                OnloglevelChanging(value);
                ReportPropertyChanging("loglevel");
                _loglevel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("loglevel");
                OnloglevelChanged();
            }
        }
        private global::System.String _loglevel;
        partial void OnloglevelChanging(global::System.String value);
        partial void OnloglevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String logger
        {
            get
            {
                return _logger;
            }
            set
            {
                OnloggerChanging(value);
                ReportPropertyChanging("logger");
                _logger = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("logger");
                OnloggerChanged();
            }
        }
        private global::System.String _logger;
        partial void OnloggerChanging(global::System.String value);
        partial void OnloggerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String exceptionmessage
        {
            get
            {
                return _exceptionmessage;
            }
            set
            {
                OnexceptionmessageChanging(value);
                ReportPropertyChanging("exceptionmessage");
                _exceptionmessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("exceptionmessage");
                OnexceptionmessageChanged();
            }
        }
        private global::System.String _exceptionmessage;
        partial void OnexceptionmessageChanging(global::System.String value);
        partial void OnexceptionmessageChanged();

        #endregion
    
    }

    #endregion
    
}
