//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DX_DOCBOXModel", "FK__DX_USERDE__depti__22AA2996", "DX_DEPARTMENT", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(docbox.Models.DX_DEPARTMENT), "DX_USERDEPT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(docbox.Models.DX_USERDEPT), true)]
[assembly: EdmRelationshipAttribute("DX_DOCBOXModel", "FK__DX_FILES__locked__060DEAE8", "DX_USER", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(docbox.Models.DX_USER), "DX_FILES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(docbox.Models.DX_FILES), true)]
[assembly: EdmRelationshipAttribute("DX_DOCBOXModel", "FK__DX_FILES__owneri__07020F21", "DX_USER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(docbox.Models.DX_USER), "DX_FILES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(docbox.Models.DX_FILES), true)]
[assembly: EdmRelationshipAttribute("DX_DOCBOXModel", "FK__DX_FILEVE__filei__182C9B23", "DX_FILES", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(docbox.Models.DX_FILES), "DX_FILEVERSION", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(docbox.Models.DX_FILEVERSION), true)]
[assembly: EdmRelationshipAttribute("DX_DOCBOXModel", "FK__DX_PRIVIL__check__0F975522", "DX_FILES", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(docbox.Models.DX_FILES), "DX_PRIVILEGE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(docbox.Models.DX_PRIVILEGE), true)]
[assembly: EdmRelationshipAttribute("DX_DOCBOXModel", "FK__DX_FILEVE__updat__1920BF5C", "DX_USER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(docbox.Models.DX_USER), "DX_FILEVERSION", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(docbox.Models.DX_FILEVERSION), true)]
[assembly: EdmRelationshipAttribute("DX_DOCBOXModel", "FK__DX_PRIVIL__useri__108B795B", "DX_USER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(docbox.Models.DX_USER), "DX_PRIVILEGE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(docbox.Models.DX_PRIVILEGE), true)]
[assembly: EdmRelationshipAttribute("DX_DOCBOXModel", "FK__DX_USERDE__useri__21B6055D", "DX_USER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(docbox.Models.DX_USER), "DX_USERDEPT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(docbox.Models.DX_USERDEPT), true)]

#endregion

namespace docbox.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dx_docboxEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dx_docboxEntities object using the connection string found in the 'dx_docboxEntities' section of the application configuration file.
        /// </summary>
        public dx_docboxEntities() : base("name=dx_docboxEntities", "dx_docboxEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dx_docboxEntities object.
        /// </summary>
        public dx_docboxEntities(string connectionString) : base(connectionString, "dx_docboxEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dx_docboxEntities object.
        /// </summary>
        public dx_docboxEntities(EntityConnection connection) : base(connection, "dx_docboxEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DX_DEPARTMENT> DX_DEPARTMENT
        {
            get
            {
                if ((_DX_DEPARTMENT == null))
                {
                    _DX_DEPARTMENT = base.CreateObjectSet<DX_DEPARTMENT>("DX_DEPARTMENT");
                }
                return _DX_DEPARTMENT;
            }
        }
        private ObjectSet<DX_DEPARTMENT> _DX_DEPARTMENT;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DX_FILES> DX_FILES
        {
            get
            {
                if ((_DX_FILES == null))
                {
                    _DX_FILES = base.CreateObjectSet<DX_FILES>("DX_FILES");
                }
                return _DX_FILES;
            }
        }
        private ObjectSet<DX_FILES> _DX_FILES;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DX_FILEVERSION> DX_FILEVERSION
        {
            get
            {
                if ((_DX_FILEVERSION == null))
                {
                    _DX_FILEVERSION = base.CreateObjectSet<DX_FILEVERSION>("DX_FILEVERSION");
                }
                return _DX_FILEVERSION;
            }
        }
        private ObjectSet<DX_FILEVERSION> _DX_FILEVERSION;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DX_PRIVILEGE> DX_PRIVILEGE
        {
            get
            {
                if ((_DX_PRIVILEGE == null))
                {
                    _DX_PRIVILEGE = base.CreateObjectSet<DX_PRIVILEGE>("DX_PRIVILEGE");
                }
                return _DX_PRIVILEGE;
            }
        }
        private ObjectSet<DX_PRIVILEGE> _DX_PRIVILEGE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DX_USER> DX_USER
        {
            get
            {
                if ((_DX_USER == null))
                {
                    _DX_USER = base.CreateObjectSet<DX_USER>("DX_USER");
                }
                return _DX_USER;
            }
        }
        private ObjectSet<DX_USER> _DX_USER;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DX_USERDEPT> DX_USERDEPT
        {
            get
            {
                if ((_DX_USERDEPT == null))
                {
                    _DX_USERDEPT = base.CreateObjectSet<DX_USERDEPT>("DX_USERDEPT");
                }
                return _DX_USERDEPT;
            }
        }
        private ObjectSet<DX_USERDEPT> _DX_USERDEPT;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DX_DEPARTMENT EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDX_DEPARTMENT(DX_DEPARTMENT dX_DEPARTMENT)
        {
            base.AddObject("DX_DEPARTMENT", dX_DEPARTMENT);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DX_FILES EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDX_FILES(DX_FILES dX_FILES)
        {
            base.AddObject("DX_FILES", dX_FILES);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DX_FILEVERSION EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDX_FILEVERSION(DX_FILEVERSION dX_FILEVERSION)
        {
            base.AddObject("DX_FILEVERSION", dX_FILEVERSION);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DX_PRIVILEGE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDX_PRIVILEGE(DX_PRIVILEGE dX_PRIVILEGE)
        {
            base.AddObject("DX_PRIVILEGE", dX_PRIVILEGE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DX_USER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDX_USER(DX_USER dX_USER)
        {
            base.AddObject("DX_USER", dX_USER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DX_USERDEPT EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDX_USERDEPT(DX_USERDEPT dX_USERDEPT)
        {
            base.AddObject("DX_USERDEPT", dX_USERDEPT);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DX_DOCBOXModel", Name="DX_DEPARTMENT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DX_DEPARTMENT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DX_DEPARTMENT object.
        /// </summary>
        /// <param name="deptid">Initial value of the deptid property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static DX_DEPARTMENT CreateDX_DEPARTMENT(global::System.Int32 deptid, global::System.String name)
        {
            DX_DEPARTMENT dX_DEPARTMENT = new DX_DEPARTMENT();
            dX_DEPARTMENT.deptid = deptid;
            dX_DEPARTMENT.name = name;
            return dX_DEPARTMENT;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 deptid
        {
            get
            {
                return _deptid;
            }
            set
            {
                if (_deptid != value)
                {
                    OndeptidChanging(value);
                    ReportPropertyChanging("deptid");
                    _deptid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("deptid");
                    OndeptidChanged();
                }
            }
        }
        private global::System.Int32 _deptid;
        partial void OndeptidChanging(global::System.Int32 value);
        partial void OndeptidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DX_DOCBOXModel", "FK__DX_USERDE__depti__22AA2996", "DX_USERDEPT")]
        public EntityCollection<DX_USERDEPT> DX_USERDEPT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DX_USERDEPT>("DX_DOCBOXModel.FK__DX_USERDE__depti__22AA2996", "DX_USERDEPT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DX_USERDEPT>("DX_DOCBOXModel.FK__DX_USERDE__depti__22AA2996", "DX_USERDEPT", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DX_DOCBOXModel", Name="DX_FILES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DX_FILES : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DX_FILES object.
        /// </summary>
        /// <param name="fileid">Initial value of the fileid property.</param>
        /// <param name="filename">Initial value of the filename property.</param>
        /// <param name="parentpath">Initial value of the parentpath property.</param>
        /// <param name="ownerid">Initial value of the ownerid property.</param>
        /// <param name="size">Initial value of the size property.</param>
        /// <param name="isarchived">Initial value of the isarchived property.</param>
        /// <param name="islocked">Initial value of the islocked property.</param>
        /// <param name="type">Initial value of the type property.</param>
        /// <param name="creationdate">Initial value of the creationdate property.</param>
        public static DX_FILES CreateDX_FILES(global::System.Int64 fileid, global::System.String filename, global::System.String parentpath, global::System.String ownerid, global::System.Int64 size, global::System.String isarchived, global::System.String islocked, global::System.String type, global::System.DateTime creationdate)
        {
            DX_FILES dX_FILES = new DX_FILES();
            dX_FILES.fileid = fileid;
            dX_FILES.filename = filename;
            dX_FILES.parentpath = parentpath;
            dX_FILES.ownerid = ownerid;
            dX_FILES.size = size;
            dX_FILES.isarchived = isarchived;
            dX_FILES.islocked = islocked;
            dX_FILES.type = type;
            dX_FILES.creationdate = creationdate;
            return dX_FILES;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 fileid
        {
            get
            {
                return _fileid;
            }
            set
            {
                if (_fileid != value)
                {
                    OnfileidChanging(value);
                    ReportPropertyChanging("fileid");
                    _fileid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fileid");
                    OnfileidChanged();
                }
            }
        }
        private global::System.Int64 _fileid;
        partial void OnfileidChanging(global::System.Int64 value);
        partial void OnfileidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String filename
        {
            get
            {
                return _filename;
            }
            set
            {
                OnfilenameChanging(value);
                ReportPropertyChanging("filename");
                _filename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("filename");
                OnfilenameChanged();
            }
        }
        private global::System.String _filename;
        partial void OnfilenameChanging(global::System.String value);
        partial void OnfilenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String parentpath
        {
            get
            {
                return _parentpath;
            }
            set
            {
                OnparentpathChanging(value);
                ReportPropertyChanging("parentpath");
                _parentpath = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("parentpath");
                OnparentpathChanged();
            }
        }
        private global::System.String _parentpath;
        partial void OnparentpathChanging(global::System.String value);
        partial void OnparentpathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ownerid
        {
            get
            {
                return _ownerid;
            }
            set
            {
                OnowneridChanging(value);
                ReportPropertyChanging("ownerid");
                _ownerid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ownerid");
                OnowneridChanged();
            }
        }
        private global::System.String _ownerid;
        partial void OnowneridChanging(global::System.String value);
        partial void OnowneridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 size
        {
            get
            {
                return _size;
            }
            set
            {
                OnsizeChanging(value);
                ReportPropertyChanging("size");
                _size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("size");
                OnsizeChanged();
            }
        }
        private global::System.Int64 _size;
        partial void OnsizeChanging(global::System.Int64 value);
        partial void OnsizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String isarchived
        {
            get
            {
                return _isarchived;
            }
            set
            {
                OnisarchivedChanging(value);
                ReportPropertyChanging("isarchived");
                _isarchived = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("isarchived");
                OnisarchivedChanged();
            }
        }
        private global::System.String _isarchived;
        partial void OnisarchivedChanging(global::System.String value);
        partial void OnisarchivedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String islocked
        {
            get
            {
                return _islocked;
            }
            set
            {
                OnislockedChanging(value);
                ReportPropertyChanging("islocked");
                _islocked = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("islocked");
                OnislockedChanged();
            }
        }
        private global::System.String _islocked;
        partial void OnislockedChanging(global::System.String value);
        partial void OnislockedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lockedby
        {
            get
            {
                return _lockedby;
            }
            set
            {
                OnlockedbyChanging(value);
                ReportPropertyChanging("lockedby");
                _lockedby = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lockedby");
                OnlockedbyChanged();
            }
        }
        private global::System.String _lockedby;
        partial void OnlockedbyChanging(global::System.String value);
        partial void OnlockedbyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime creationdate
        {
            get
            {
                return _creationdate;
            }
            set
            {
                OncreationdateChanging(value);
                ReportPropertyChanging("creationdate");
                _creationdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("creationdate");
                OncreationdateChanged();
            }
        }
        private global::System.DateTime _creationdate;
        partial void OncreationdateChanging(global::System.DateTime value);
        partial void OncreationdateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DX_DOCBOXModel", "FK__DX_FILES__locked__060DEAE8", "DX_USER")]
        public DX_USER DX_USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_FILES__locked__060DEAE8", "DX_USER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_FILES__locked__060DEAE8", "DX_USER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DX_USER> DX_USERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_FILES__locked__060DEAE8", "DX_USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_FILES__locked__060DEAE8", "DX_USER", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DX_DOCBOXModel", "FK__DX_FILES__owneri__07020F21", "DX_USER")]
        public DX_USER DX_USER1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_FILES__owneri__07020F21", "DX_USER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_FILES__owneri__07020F21", "DX_USER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DX_USER> DX_USER1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_FILES__owneri__07020F21", "DX_USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_FILES__owneri__07020F21", "DX_USER", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DX_DOCBOXModel", "FK__DX_FILEVE__filei__182C9B23", "DX_FILEVERSION")]
        public EntityCollection<DX_FILEVERSION> DX_FILEVERSION
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DX_FILEVERSION>("DX_DOCBOXModel.FK__DX_FILEVE__filei__182C9B23", "DX_FILEVERSION");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DX_FILEVERSION>("DX_DOCBOXModel.FK__DX_FILEVE__filei__182C9B23", "DX_FILEVERSION", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DX_DOCBOXModel", "FK__DX_PRIVIL__check__0F975522", "DX_PRIVILEGE")]
        public EntityCollection<DX_PRIVILEGE> DX_PRIVILEGE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DX_PRIVILEGE>("DX_DOCBOXModel.FK__DX_PRIVIL__check__0F975522", "DX_PRIVILEGE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DX_PRIVILEGE>("DX_DOCBOXModel.FK__DX_PRIVIL__check__0F975522", "DX_PRIVILEGE", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DX_DOCBOXModel", Name="DX_FILEVERSION")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DX_FILEVERSION : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DX_FILEVERSION object.
        /// </summary>
        /// <param name="version">Initial value of the version property.</param>
        /// <param name="fileid">Initial value of the fileid property.</param>
        /// <param name="versionid">Initial value of the versionid property.</param>
        /// <param name="versionnumber">Initial value of the versionnumber property.</param>
        /// <param name="updatedate">Initial value of the updatedate property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="size">Initial value of the size property.</param>
        /// <param name="updatedby">Initial value of the updatedby property.</param>
        /// <param name="isencrypted">Initial value of the isencrypted property.</param>
        public static DX_FILEVERSION CreateDX_FILEVERSION(global::System.Int64 version, global::System.Int64 fileid, global::System.Guid versionid, global::System.Int32 versionnumber, global::System.DateTime updatedate, global::System.String description, global::System.Int32 size, global::System.String updatedby, global::System.String isencrypted)
        {
            DX_FILEVERSION dX_FILEVERSION = new DX_FILEVERSION();
            dX_FILEVERSION.version = version;
            dX_FILEVERSION.fileid = fileid;
            dX_FILEVERSION.versionid = versionid;
            dX_FILEVERSION.versionnumber = versionnumber;
            dX_FILEVERSION.updatedate = updatedate;
            dX_FILEVERSION.description = description;
            dX_FILEVERSION.size = size;
            dX_FILEVERSION.updatedby = updatedby;
            dX_FILEVERSION.isencrypted = isencrypted;
            return dX_FILEVERSION;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 version
        {
            get
            {
                return _version;
            }
            set
            {
                if (_version != value)
                {
                    OnversionChanging(value);
                    ReportPropertyChanging("version");
                    _version = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("version");
                    OnversionChanged();
                }
            }
        }
        private global::System.Int64 _version;
        partial void OnversionChanging(global::System.Int64 value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 fileid
        {
            get
            {
                return _fileid;
            }
            set
            {
                OnfileidChanging(value);
                ReportPropertyChanging("fileid");
                _fileid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fileid");
                OnfileidChanged();
            }
        }
        private global::System.Int64 _fileid;
        partial void OnfileidChanging(global::System.Int64 value);
        partial void OnfileidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid versionid
        {
            get
            {
                return _versionid;
            }
            set
            {
                OnversionidChanging(value);
                ReportPropertyChanging("versionid");
                _versionid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("versionid");
                OnversionidChanged();
            }
        }
        private global::System.Guid _versionid;
        partial void OnversionidChanging(global::System.Guid value);
        partial void OnversionidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 versionnumber
        {
            get
            {
                return _versionnumber;
            }
            set
            {
                OnversionnumberChanging(value);
                ReportPropertyChanging("versionnumber");
                _versionnumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("versionnumber");
                OnversionnumberChanged();
            }
        }
        private global::System.Int32 _versionnumber;
        partial void OnversionnumberChanging(global::System.Int32 value);
        partial void OnversionnumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime updatedate
        {
            get
            {
                return _updatedate;
            }
            set
            {
                OnupdatedateChanging(value);
                ReportPropertyChanging("updatedate");
                _updatedate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("updatedate");
                OnupdatedateChanged();
            }
        }
        private global::System.DateTime _updatedate;
        partial void OnupdatedateChanging(global::System.DateTime value);
        partial void OnupdatedateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 size
        {
            get
            {
                return _size;
            }
            set
            {
                OnsizeChanging(value);
                ReportPropertyChanging("size");
                _size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("size");
                OnsizeChanged();
            }
        }
        private global::System.Int32 _size;
        partial void OnsizeChanging(global::System.Int32 value);
        partial void OnsizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String updatedby
        {
            get
            {
                return _updatedby;
            }
            set
            {
                OnupdatedbyChanging(value);
                ReportPropertyChanging("updatedby");
                _updatedby = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("updatedby");
                OnupdatedbyChanged();
            }
        }
        private global::System.String _updatedby;
        partial void OnupdatedbyChanging(global::System.String value);
        partial void OnupdatedbyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] filedata
        {
            get
            {
                return StructuralObject.GetValidValue(_filedata);
            }
            set
            {
                OnfiledataChanging(value);
                ReportPropertyChanging("filedata");
                _filedata = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("filedata");
                OnfiledataChanged();
            }
        }
        private global::System.Byte[] _filedata;
        partial void OnfiledataChanging(global::System.Byte[] value);
        partial void OnfiledataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String isencrypted
        {
            get
            {
                return _isencrypted;
            }
            set
            {
                OnisencryptedChanging(value);
                ReportPropertyChanging("isencrypted");
                _isencrypted = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("isencrypted");
                OnisencryptedChanged();
            }
        }
        private global::System.String _isencrypted;
        partial void OnisencryptedChanging(global::System.String value);
        partial void OnisencryptedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DX_DOCBOXModel", "FK__DX_FILEVE__filei__182C9B23", "DX_FILES")]
        public DX_FILES DX_FILES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_FILES>("DX_DOCBOXModel.FK__DX_FILEVE__filei__182C9B23", "DX_FILES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_FILES>("DX_DOCBOXModel.FK__DX_FILEVE__filei__182C9B23", "DX_FILES").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DX_FILES> DX_FILESReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_FILES>("DX_DOCBOXModel.FK__DX_FILEVE__filei__182C9B23", "DX_FILES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DX_FILES>("DX_DOCBOXModel.FK__DX_FILEVE__filei__182C9B23", "DX_FILES", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DX_DOCBOXModel", "FK__DX_FILEVE__updat__1920BF5C", "DX_USER")]
        public DX_USER DX_USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_FILEVE__updat__1920BF5C", "DX_USER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_FILEVE__updat__1920BF5C", "DX_USER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DX_USER> DX_USERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_FILEVE__updat__1920BF5C", "DX_USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_FILEVE__updat__1920BF5C", "DX_USER", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DX_DOCBOXModel", Name="DX_PRIVILEGE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DX_PRIVILEGE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DX_PRIVILEGE object.
        /// </summary>
        /// <param name="privilegeid">Initial value of the privilegeid property.</param>
        /// <param name="fileid">Initial value of the fileid property.</param>
        /// <param name="userid">Initial value of the userid property.</param>
        /// <param name="read">Initial value of the read property.</param>
        /// <param name="write">Initial value of the write property.</param>
        /// <param name="update">Initial value of the update property.</param>
        /// <param name="check">Initial value of the check property.</param>
        public static DX_PRIVILEGE CreateDX_PRIVILEGE(global::System.Int64 privilegeid, global::System.Int64 fileid, global::System.String userid, global::System.String read, global::System.String write, global::System.String update, global::System.String check)
        {
            DX_PRIVILEGE dX_PRIVILEGE = new DX_PRIVILEGE();
            dX_PRIVILEGE.privilegeid = privilegeid;
            dX_PRIVILEGE.fileid = fileid;
            dX_PRIVILEGE.userid = userid;
            dX_PRIVILEGE.read = read;
            dX_PRIVILEGE.write = write;
            dX_PRIVILEGE.update = update;
            dX_PRIVILEGE.check = check;
            return dX_PRIVILEGE;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 privilegeid
        {
            get
            {
                return _privilegeid;
            }
            set
            {
                if (_privilegeid != value)
                {
                    OnprivilegeidChanging(value);
                    ReportPropertyChanging("privilegeid");
                    _privilegeid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("privilegeid");
                    OnprivilegeidChanged();
                }
            }
        }
        private global::System.Int64 _privilegeid;
        partial void OnprivilegeidChanging(global::System.Int64 value);
        partial void OnprivilegeidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 fileid
        {
            get
            {
                return _fileid;
            }
            set
            {
                OnfileidChanging(value);
                ReportPropertyChanging("fileid");
                _fileid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fileid");
                OnfileidChanged();
            }
        }
        private global::System.Int64 _fileid;
        partial void OnfileidChanging(global::System.Int64 value);
        partial void OnfileidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userid
        {
            get
            {
                return _userid;
            }
            set
            {
                OnuseridChanging(value);
                ReportPropertyChanging("userid");
                _userid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("userid");
                OnuseridChanged();
            }
        }
        private global::System.String _userid;
        partial void OnuseridChanging(global::System.String value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String read
        {
            get
            {
                return _read;
            }
            set
            {
                OnreadChanging(value);
                ReportPropertyChanging("read");
                _read = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("read");
                OnreadChanged();
            }
        }
        private global::System.String _read;
        partial void OnreadChanging(global::System.String value);
        partial void OnreadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String write
        {
            get
            {
                return _write;
            }
            set
            {
                OnwriteChanging(value);
                ReportPropertyChanging("write");
                _write = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("write");
                OnwriteChanged();
            }
        }
        private global::System.String _write;
        partial void OnwriteChanging(global::System.String value);
        partial void OnwriteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String update
        {
            get
            {
                return _update;
            }
            set
            {
                OnupdateChanging(value);
                ReportPropertyChanging("update");
                _update = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("update");
                OnupdateChanged();
            }
        }
        private global::System.String _update;
        partial void OnupdateChanging(global::System.String value);
        partial void OnupdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String check
        {
            get
            {
                return _check;
            }
            set
            {
                OncheckChanging(value);
                ReportPropertyChanging("check");
                _check = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("check");
                OncheckChanged();
            }
        }
        private global::System.String _check;
        partial void OncheckChanging(global::System.String value);
        partial void OncheckChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DX_DOCBOXModel", "FK__DX_PRIVIL__check__0F975522", "DX_FILES")]
        public DX_FILES DX_FILES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_FILES>("DX_DOCBOXModel.FK__DX_PRIVIL__check__0F975522", "DX_FILES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_FILES>("DX_DOCBOXModel.FK__DX_PRIVIL__check__0F975522", "DX_FILES").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DX_FILES> DX_FILESReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_FILES>("DX_DOCBOXModel.FK__DX_PRIVIL__check__0F975522", "DX_FILES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DX_FILES>("DX_DOCBOXModel.FK__DX_PRIVIL__check__0F975522", "DX_FILES", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DX_DOCBOXModel", "FK__DX_PRIVIL__useri__108B795B", "DX_USER")]
        public DX_USER DX_USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_PRIVIL__useri__108B795B", "DX_USER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_PRIVIL__useri__108B795B", "DX_USER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DX_USER> DX_USERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_PRIVIL__useri__108B795B", "DX_USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_PRIVIL__useri__108B795B", "DX_USER", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DX_DOCBOXModel", Name="DX_USER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DX_USER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DX_USER object.
        /// </summary>
        /// <param name="userid">Initial value of the userid property.</param>
        /// <param name="fname">Initial value of the fname property.</param>
        /// <param name="lname">Initial value of the lname property.</param>
        /// <param name="role">Initial value of the role property.</param>
        /// <param name="pwdhash">Initial value of the pwdhash property.</param>
        /// <param name="questionid">Initial value of the questionid property.</param>
        /// <param name="phone">Initial value of the phone property.</param>
        /// <param name="anshash">Initial value of the anshash property.</param>
        /// <param name="accesslevel">Initial value of the accesslevel property.</param>
        /// <param name="salt">Initial value of the salt property.</param>
        public static DX_USER CreateDX_USER(global::System.String userid, global::System.String fname, global::System.String lname, global::System.String role, global::System.String pwdhash, global::System.Int32 questionid, global::System.String phone, global::System.String anshash, global::System.String accesslevel, global::System.String salt)
        {
            DX_USER dX_USER = new DX_USER();
            dX_USER.userid = userid;
            dX_USER.fname = fname;
            dX_USER.lname = lname;
            dX_USER.role = role;
            dX_USER.pwdhash = pwdhash;
            dX_USER.questionid = questionid;
            dX_USER.phone = phone;
            dX_USER.anshash = anshash;
            dX_USER.accesslevel = accesslevel;
            dX_USER.salt = salt;
            return dX_USER;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userid
        {
            get
            {
                return _userid;
            }
            set
            {
                if (_userid != value)
                {
                    OnuseridChanging(value);
                    ReportPropertyChanging("userid");
                    _userid = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("userid");
                    OnuseridChanged();
                }
            }
        }
        private global::System.String _userid;
        partial void OnuseridChanging(global::System.String value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String fname
        {
            get
            {
                return _fname;
            }
            set
            {
                OnfnameChanging(value);
                ReportPropertyChanging("fname");
                _fname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("fname");
                OnfnameChanged();
            }
        }
        private global::System.String _fname;
        partial void OnfnameChanging(global::System.String value);
        partial void OnfnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lname
        {
            get
            {
                return _lname;
            }
            set
            {
                OnlnameChanging(value);
                ReportPropertyChanging("lname");
                _lname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lname");
                OnlnameChanged();
            }
        }
        private global::System.String _lname;
        partial void OnlnameChanging(global::System.String value);
        partial void OnlnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String role
        {
            get
            {
                return _role;
            }
            set
            {
                OnroleChanging(value);
                ReportPropertyChanging("role");
                _role = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("role");
                OnroleChanged();
            }
        }
        private global::System.String _role;
        partial void OnroleChanging(global::System.String value);
        partial void OnroleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pwdhash
        {
            get
            {
                return _pwdhash;
            }
            set
            {
                OnpwdhashChanging(value);
                ReportPropertyChanging("pwdhash");
                _pwdhash = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("pwdhash");
                OnpwdhashChanged();
            }
        }
        private global::System.String _pwdhash;
        partial void OnpwdhashChanging(global::System.String value);
        partial void OnpwdhashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 questionid
        {
            get
            {
                return _questionid;
            }
            set
            {
                OnquestionidChanging(value);
                ReportPropertyChanging("questionid");
                _questionid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("questionid");
                OnquestionidChanged();
            }
        }
        private global::System.Int32 _questionid;
        partial void OnquestionidChanging(global::System.Int32 value);
        partial void OnquestionidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String anshash
        {
            get
            {
                return _anshash;
            }
            set
            {
                OnanshashChanging(value);
                ReportPropertyChanging("anshash");
                _anshash = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("anshash");
                OnanshashChanged();
            }
        }
        private global::System.String _anshash;
        partial void OnanshashChanging(global::System.String value);
        partial void OnanshashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String actcodehash
        {
            get
            {
                return _actcodehash;
            }
            set
            {
                OnactcodehashChanging(value);
                ReportPropertyChanging("actcodehash");
                _actcodehash = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("actcodehash");
                OnactcodehashChanged();
            }
        }
        private global::System.String _actcodehash;
        partial void OnactcodehashChanging(global::System.String value);
        partial void OnactcodehashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String accesslevel
        {
            get
            {
                return _accesslevel;
            }
            set
            {
                OnaccesslevelChanging(value);
                ReportPropertyChanging("accesslevel");
                _accesslevel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("accesslevel");
                OnaccesslevelChanged();
            }
        }
        private global::System.String _accesslevel;
        partial void OnaccesslevelChanging(global::System.String value);
        partial void OnaccesslevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String salt
        {
            get
            {
                return _salt;
            }
            set
            {
                OnsaltChanging(value);
                ReportPropertyChanging("salt");
                _salt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("salt");
                OnsaltChanged();
            }
        }
        private global::System.String _salt;
        partial void OnsaltChanging(global::System.String value);
        partial void OnsaltChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DX_DOCBOXModel", "FK__DX_FILES__locked__060DEAE8", "DX_FILES")]
        public EntityCollection<DX_FILES> DX_FILES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DX_FILES>("DX_DOCBOXModel.FK__DX_FILES__locked__060DEAE8", "DX_FILES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DX_FILES>("DX_DOCBOXModel.FK__DX_FILES__locked__060DEAE8", "DX_FILES", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DX_DOCBOXModel", "FK__DX_FILES__owneri__07020F21", "DX_FILES")]
        public EntityCollection<DX_FILES> DX_FILES1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DX_FILES>("DX_DOCBOXModel.FK__DX_FILES__owneri__07020F21", "DX_FILES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DX_FILES>("DX_DOCBOXModel.FK__DX_FILES__owneri__07020F21", "DX_FILES", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DX_DOCBOXModel", "FK__DX_FILEVE__updat__1920BF5C", "DX_FILEVERSION")]
        public EntityCollection<DX_FILEVERSION> DX_FILEVERSION
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DX_FILEVERSION>("DX_DOCBOXModel.FK__DX_FILEVE__updat__1920BF5C", "DX_FILEVERSION");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DX_FILEVERSION>("DX_DOCBOXModel.FK__DX_FILEVE__updat__1920BF5C", "DX_FILEVERSION", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DX_DOCBOXModel", "FK__DX_PRIVIL__useri__108B795B", "DX_PRIVILEGE")]
        public EntityCollection<DX_PRIVILEGE> DX_PRIVILEGE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DX_PRIVILEGE>("DX_DOCBOXModel.FK__DX_PRIVIL__useri__108B795B", "DX_PRIVILEGE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DX_PRIVILEGE>("DX_DOCBOXModel.FK__DX_PRIVIL__useri__108B795B", "DX_PRIVILEGE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DX_DOCBOXModel", "FK__DX_USERDE__useri__21B6055D", "DX_USERDEPT")]
        public EntityCollection<DX_USERDEPT> DX_USERDEPT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DX_USERDEPT>("DX_DOCBOXModel.FK__DX_USERDE__useri__21B6055D", "DX_USERDEPT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DX_USERDEPT>("DX_DOCBOXModel.FK__DX_USERDE__useri__21B6055D", "DX_USERDEPT", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DX_DOCBOXModel", Name="DX_USERDEPT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DX_USERDEPT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DX_USERDEPT object.
        /// </summary>
        /// <param name="userdeptid">Initial value of the userdeptid property.</param>
        /// <param name="userid">Initial value of the userid property.</param>
        /// <param name="deptid">Initial value of the deptid property.</param>
        public static DX_USERDEPT CreateDX_USERDEPT(global::System.Int64 userdeptid, global::System.String userid, global::System.Int32 deptid)
        {
            DX_USERDEPT dX_USERDEPT = new DX_USERDEPT();
            dX_USERDEPT.userdeptid = userdeptid;
            dX_USERDEPT.userid = userid;
            dX_USERDEPT.deptid = deptid;
            return dX_USERDEPT;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userdeptid
        {
            get
            {
                return _userdeptid;
            }
            set
            {
                if (_userdeptid != value)
                {
                    OnuserdeptidChanging(value);
                    ReportPropertyChanging("userdeptid");
                    _userdeptid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userdeptid");
                    OnuserdeptidChanged();
                }
            }
        }
        private global::System.Int64 _userdeptid;
        partial void OnuserdeptidChanging(global::System.Int64 value);
        partial void OnuserdeptidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userid
        {
            get
            {
                return _userid;
            }
            set
            {
                OnuseridChanging(value);
                ReportPropertyChanging("userid");
                _userid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("userid");
                OnuseridChanged();
            }
        }
        private global::System.String _userid;
        partial void OnuseridChanging(global::System.String value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 deptid
        {
            get
            {
                return _deptid;
            }
            set
            {
                OndeptidChanging(value);
                ReportPropertyChanging("deptid");
                _deptid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("deptid");
                OndeptidChanged();
            }
        }
        private global::System.Int32 _deptid;
        partial void OndeptidChanging(global::System.Int32 value);
        partial void OndeptidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DX_DOCBOXModel", "FK__DX_USERDE__depti__22AA2996", "DX_DEPARTMENT")]
        public DX_DEPARTMENT DX_DEPARTMENT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_DEPARTMENT>("DX_DOCBOXModel.FK__DX_USERDE__depti__22AA2996", "DX_DEPARTMENT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_DEPARTMENT>("DX_DOCBOXModel.FK__DX_USERDE__depti__22AA2996", "DX_DEPARTMENT").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DX_DEPARTMENT> DX_DEPARTMENTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_DEPARTMENT>("DX_DOCBOXModel.FK__DX_USERDE__depti__22AA2996", "DX_DEPARTMENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DX_DEPARTMENT>("DX_DOCBOXModel.FK__DX_USERDE__depti__22AA2996", "DX_DEPARTMENT", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DX_DOCBOXModel", "FK__DX_USERDE__useri__21B6055D", "DX_USER")]
        public DX_USER DX_USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_USERDE__useri__21B6055D", "DX_USER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_USERDE__useri__21B6055D", "DX_USER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DX_USER> DX_USERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_USERDE__useri__21B6055D", "DX_USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DX_USER>("DX_DOCBOXModel.FK__DX_USERDE__useri__21B6055D", "DX_USER", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
